export const routes = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  PROFILE: '/profile',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:uid/:token',
  ACTIVATE_USER: '/activate/:uid/:token',
  VERIFY: '/verify',
  TERMS_AND_CONDITIONS: '/terms-and-conditions',
  SETTINGS: '/settings',
  PRODUCTS: '/products',
  PRODUCT: (id: number | string) => `/product/${id}`,
  PACKAGES: '/packages',
  PACKAGE: (id: number | string) => `/package/${id}`,
  SUBSCRIPTIONS: '/subscriptions',
  PAYMENT_SUCCESSFUL: '/payment-successful',
  PAYMENT_FAILED: '/payment-failed',
  INVOICES: '/invoices',
  INVOICE: (id: number | string) => `/invoice/${id}`,
  REFUNDS: '/refunds',
  PAYMENT_METHODS: '/payment-methods',
  MODULES: '/modules',
  MODULE: (name: string) => `/module/${name}`,
};
